添加了专门面向小白的编译文档
waylyrics/waylyrics pull request #240
Opened 2024-06-01 12:40 UTC by xmb505

2024-06-01 13:05 UTC, mokurin000 commented
网络问题其实可以考虑为 cargo 设置字节跳动的镜像
刚刚仔细看了一遍，之前写的教程确实什么地方要做什么都是假设用户能自己理解，再提供详细命令 这份教程写的很棒！

2024-06-01 13:10 UTC, xmb505 commented
拿我添加一个换源的吧，主要是没接触过rust，我自己编译的时候脑袋也蒙住了

2024-06-01 13:22 UTC, xmb505 reviewed
更新了 cargo 换源上交大

2024-06-01 13:28 UTC, mokurin000 commented
@xmb505 rsproxy.cn 看下？

2024-06-01 13:35 UTC, xmb505 reviewed
更换源到https://rsproxy.cn/

2024-06-02 16:01 UTC, mokurin000 commented
@xmb505 hi~ 有空时记得看下review？

2024-06-02 16:02 UTC, xmb505 commented
什么是review？

2024-06-02 16:06 UTC, xmb505 commented
还有哪里有什么问题嘛？

2024-06-02 16:08 UTC, mokurin000 commented
> 什么是review？

![image](https://github.com/waylyrics/waylyrics/assets/34085039/e14fba28-fc1e-43ba-a0cd-2531a0e3e66f)

2024-06-02 16:10 UTC, xmb505 commented
为毛我看不见![Screenshot_2024-06-03-00-10-18-298_com.github.android.jpg](https://github.com/waylyrics/waylyrics/assets/69708490/6b44ffce-1fa0-4496-a674-f9ebcbb6e9fe)

2024-06-02 16:12 UTC, mokurin000 commented
> 为毛我看不见![Screenshot_2024-06-03-00-10-18-298_com.github.android.jpg](https://private-user-images.githubusercontent.com/69708490/335881052-6b44ffce-1fa0-4496-a674-f9ebcbb6e9fe.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczNDQ5NTYsIm5iZiI6MTcxNzM0NDY1NiwicGF0aCI6Ii82OTcwODQ5MC8zMzU4ODEwNTItNmI0NGZmY2UtMWZhMC00NDk2LWE2NzQtZjllYmNiYjZlOWZlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAyVDE2MTA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3NjQ4ZWVmNzdjZDFhNWVkY2I4OWU1MzY5ZDA5NTA0NGE2ZDM0NDNiOWU2Nzg5ZGI5YjRmOWRlYWZmODg1ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YYR_LE8kAnfAdHmEuNVqACIeL9-s0zqtijd2DxxlXdw)

不清楚，我这里是pending状态，之前taoky给你的pr review时这个客户端是可以显示的吗？

2024-06-02 16:13 UTC, mokurin000 commented
@xmb505 taoky跟我说了，还有我自己搜索了一下，这里的review要到change页提交你才能看到。。。

2024-06-02 16:13 UTC, xmb505 commented
之前我用的是笔记本操作，现在上床睡觉了，我今天一天也没收到邮件啊（怪）

2024-06-02 16:16 UTC, mokurin000 commented
> 之前我用的是笔记本操作，现在上床睡觉了，我今天一天也没收到邮件啊（怪）

现在应该可以了，我之前一直没有 submit，不常用Github这东西... 原来评论后还需要submit过去

2024-06-02 16:24 UTC, mokurin000 commented on doc/BUILD_GUIDE_UBUNTU.zh_cn.md
> +cp ./metainfo/io.github.waylyrics.Waylyrics.gschema.xml /usr/share/glib-2.0/schemas
一个社区惯用的路径是 ~/.local/bin
这里还要检查 $PATH 是否已设置该路径

2024-06-02 16:34 UTC, mokurin000 commented on doc/BUILD_GUIDE_UBUNTU.zh_cn.md
> +在 Linux 下， /bin 文件夹下放着很多可执行文件，比如 apt 、 grep 等命令，我们把 waylyrics 的二进制文件复制到 /bin 目录下，这样我们就可以直接使用 waylyrics 命令启动 Waylyrics 程序。
另见 stackexchange[^0]
[^0]: https://unix.stackexchange.com/questions/5915/difference-between-bin-and-usr-bin

2024-06-02 16:37 UTC, mokurin000 commented on doc/BUILD_GUIDE_UBUNTU.zh_cn.md
> +在 Linux 下， /bin 文件夹下放着很多可执行文件，比如 apt 、 grep 等命令，我们把 waylyrics 的二进制文件复制到 /usr/bin 目录下，然后将我们编译好的软件创建符号链接指向 /bin ，这样我们就可以直接使用 waylyrics 命令启动 Waylyrics 程序。
诶？...
不需要手动到 /bin/ 建立链接到 waylyrics二进制啊
/usr/bin 的二进制在多用户引导模式一定会在 PATH 中的

2024-06-02 16:59 UTC, xmb505 reviewed
晚安，明见（懒得在评论里面写markdown了）

2024-06-02 16:59 UTC, xmb505 commented on doc/BUILD_GUIDE_UBUNTU.zh_cn.md
> +在 Linux 下， /bin 文件夹下放着很多可执行文件，比如 apt 、 grep 等命令，我们把 waylyrics 的二进制文件复制到 /usr/bin 目录下，然后将我们编译好的软件创建符号链接指向 /bin ，这样我们就可以直接使用 waylyrics 命令启动 Waylyrics 程序。
尊嘟假嘟，我Ubuntu 2204并不会去执行/usr/bin下的文件，如果只把软件放在/usr/bin下面，直接输入命令是不会执行的，而是会提示你/usr/bin下有同名软件

2024-06-02 16:59 UTC, xmb505 commented on doc/BUILD_GUIDE_UBUNTU.zh_cn.md
> +cp ./metainfo/io.github.waylyrics.Waylyrics.gschema.xml /usr/share/glib-2.0/schemas
啊？文章开头已经说过了此文章默认全局安装，如果高阶玩家想要个人安装也点名了可以安装到~/.local/share里面，主要是~/.local/share根本也没几个软件用啊，这样还需要手动mkdir总感觉有些不合适。

2024-06-02 16:59 UTC, xmb505 commented on doc/BUILD_GUIDE_UBUNTU.zh_cn.md
> +在 Linux 下， /bin 文件夹下放着很多可执行文件，比如 apt 、 grep 等命令，我们把 waylyrics 的二进制文件复制到 /usr/bin 目录下，然后将我们编译好的软件创建符号链接指向 /bin ，这样我们就可以直接使用 waylyrics 命令启动 Waylyrics 程序。
我打包到aptss上的waylyrics.deb就是直接把二进制丢bin里面，全局安装，卸载的时候也是干干净净不留痕迹，只有包管理安装的文件才会被标记吧，手动编译的不会

2024-06-02 16:59 UTC, xmb505 commented on doc/BUILD_GUIDE_UBUNTU.zh_cn.md
> +mkdir -p /usr/share/waylyrics/themes/
在clone源码的时候已经提到了，不过还是需要给高级玩家提一嘴

2024-06-02 17:22 UTC, mokurin000 commented on doc/BUILD_GUIDE_UBUNTU.zh_cn.md
> +cp ./metainfo/io.github.waylyrics.Waylyrics.gschema.xml /usr/share/glib-2.0/schemas
> 啊？文章开头已经说过了此文章默认全局安装，如果高阶玩家想要个人安装也点名了可以安装到~/.local/share里面，主要是~/.local/share根本也没几个软件用啊，这样还需要手动mkdir总感觉有些不合适。

确实 ~/.local/bin 一般是 python 的东西放在这里...
主要是会导致 /usr/bin/waylyrics 对于系统包管理文件未追踪，不过作为二进制+glib schemas+share/xxxx/，其他包很难遇到文件冲突（除非waylyrics被ubuntu用户打包）
那就先保持这样好

2024-06-02 17:24 UTC, mokurin000 commented on doc/BUILD_GUIDE_UBUNTU.zh_cn.md
> +mkdir -p /usr/share/waylyrics/themes/
> 在clone源码的时候已经提到了，不过还是需要给高级玩家提一嘴

啊... 我漏看了

2024-06-02 17:40 UTC, mokurin000 commented on doc/BUILD_GUIDE_UBUNTU.zh_cn.md
> +保持 Waylyrics 窗口状态，右键其标题栏，选择更多，选中置顶，然后关闭其窗口状态就可以实现歌词置顶。
KDE用户可以这样操作，GNOME/其他桌面环境会有些许不同：
GNOME用户需要安装拓展才能支持手动为窗口设置置顶（他们为了阻止用户影响GNOME的UI组件统一视觉风格不顾一切）
其他窗口管理用户需要参照 https://github.com/waylyrics/waylyrics/discussions/181

2024-06-02 17:51 UTC, mokurin000 commented on doc/BUILD_GUIDE_UBUNTU.zh_cn.md
> +保持 Waylyrics 窗口状态，右键其标题栏，选择更多，选中置顶，然后关闭其窗口状态就可以实现歌词置顶。
```diff
- 保持 Waylyrics 窗口状态，右键其标题栏，选择更多，选中置顶，然后关闭其窗口状态就可以实现歌词置顶。
+ KDE用户：保持 Waylyrics 窗口状态，右键其标题栏，选择更多，选中置顶，然后关闭其窗口状态就可以实现歌词置顶。也可以添加https://github.com/waylyrics/waylyrics/discussions/181，这样可以持续置顶
```

2024-06-02 17:51 UTC, mokurin000 requested changes

2024-06-02 17:51 UTC, mokurin000 commented on doc/BUILD_GUIDE_UBUNTU.zh_cn.md
> +保持 Waylyrics 窗口状态，右键其标题栏，选择更多，选中置顶，然后关闭其窗口状态就可以实现歌词置顶。
```diff
- 保持 Waylyrics 窗口状态，右键其标题栏，选择更多，选中置顶，然后关闭其窗口状态就可以实现歌词置顶。
+ KDE用户：保持 Waylyrics 窗口状态，右键其标题栏，选择更多，选中置顶，然后关闭其窗口状态就可以实现歌词置顶。也可以添加https://github.com/waylyrics/waylyrics/discussions/181，这样可以持续置顶
```

2024-06-03 00:10 UTC, xmb505 reviewed
大致看了一下应该没什么问题了似乎

2024-06-03 01:08 UTC, mokurin000 approved these changes

2024-06-03 01:10 UTC, merged